In [79]:
import pandas as pd
import math
import csv
import numpy as np

In [102]:
co2 = pd.read_excel('API_EN.ATM.CO2E.PC_DS2_en_excel_v2_10515462.xls')
population = pd.read_excel('API_SP.POP.TOTL_DS2_en_excel_v2_10515202.xls')

In [74]:

for i in range(1960, 2018):
    string = str(i)
    if i < 2006 or i > 2014:
        del co2[string]
        del population[string]

print(co2)

                                          Country Name Country Code  \
0                                                Aruba          ABW
1                                          Afghanistan          AFG
2                                               Angola          AGO
3                                              Albania          ALB
4                                              Andorra          AND
5                                           Arab World          ARB
6                                 United Arab Emirates          ARE
7                                            Argentina          ARG
8                                              Armenia          ARM
9                                       American Samoa          ASM
10                                 Antigua and Barbuda          ATG
11                                           Australia          AUS
12                                             Austria          AUT
13                                          Azerbaijan          AZE
14                                             Burundi          BDI
15                                             Belgium          BEL
16                                               Benin          BEN
17                                        Burkina Faso          BFA
18                                          Bangladesh          BGD
19                                            Bulgaria          BGR
20                                             Bahrain          BHR
21                                        Bahamas, The          BHS
22                              Bosnia and Herzegovina          BIH
23                                             Belarus          BLR
24                                              Belize          BLZ
25                                             Bermuda          BMU
26                                             Bolivia          BOL
27                                              Brazil          BRA
28                                            Barbados          BRB
29                                   Brunei Darussalam          BRN
..                                                 ...          ...
234  Latin America & the Caribbean (IDA & IBRD coun...          TLA
235                                        Timor-Leste          TLS
236  Middle East & North Africa (IDA & IBRD countries)          TMN
237                                              Tonga          TON
238                            South Asia (IDA & IBRD)          TSA
239          Sub-Saharan Africa (IDA & IBRD countries)          TSS
240                                Trinidad and Tobago          TTO
241                                            Tunisia          TUN
242                                             Turkey          TUR
243                                             Tuvalu          TUV
244                                           Tanzania          TZA
245                                             Uganda          UGA
246                                            Ukraine          UKR
247                                Upper middle income          UMC
248                                            Uruguay          URY
249                                      United States          USA
250                                         Uzbekistan          UZB
251                     St. Vincent and the Grenadines          VCT
252                                      Venezuela, RB          VEN
253                             British Virgin Islands          VGB
254                              Virgin Islands (U.S.)          VIR
255                                            Vietnam          VNM
256                                            Vanuatu          VUT
257                                              World          WLD
258                                              Samoa          WSM
259                                             Kosovo          XKX
260                                        Yemen, Rep.          YEM
261                                       South Africa          ZAF
262                                             Zambia          ZMB
263                                           Zimbabwe          ZWE

                             Indicator Name  Indicator Code       2005  \
0    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC  27.200708
1    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.052948
2    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.979740
3    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   1.412498
4    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   7.299872
5    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   4.168486
6    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC  25.362373
7    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   4.141237
8    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   1.460030
9    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC        NaN
10   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   4.806998
11   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC  17.169711
12   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   9.020170
13   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   4.091802
14   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.020747
15   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC  10.355393
16   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.299985
17   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.083875
18   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.275247
19   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   6.256282
20   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC  21.601931
21   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   5.290297
22   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   4.285163
23   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   6.122472
24   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   1.488667
25   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   9.088334
26   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   1.335331
27   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   1.858088
28   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   4.938243
29   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC  13.707642
..                                      ...             ...        ...
234  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   2.703240
235  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.171475
236  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   3.579957
237  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   1.125058
238  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.936217
239  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.865613
240  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC  29.416661
241  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   2.243217
242  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   3.496004
243  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   1.097138
244  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.139662
245  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.076053
246  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   7.087902
247  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   4.732263
248  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   1.736680
249  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC  19.591885
250  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   4.480783
251  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   2.023284
252  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   6.163929
253  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   5.698032
254  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC        NaN
255  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   1.164096
256  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.280231
257  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   4.522801
258  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.896731
259  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC        NaN
260  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.973808
261  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   8.539756
262  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.189859
263  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.832299

          2006       2007       2008       2009       2010       2011  \
0    26.948260  27.895574  26.230847  25.915833  24.670529  24.505835
1     0.063728   0.085418   0.154101   0.241723   0.293837   0.412017
2     1.098884   1.197844   1.181527   1.232495   1.243406   1.252789
3     1.302576   1.322335   1.484311   1.495600   1.578574   1.803715
4     6.746219   6.519466   6.427887   6.121652   6.122595   5.867130
5     4.268240   4.100226   4.390401   4.542151   4.615758   4.537755
6    23.631089  22.439801  22.823947  21.908556  19.443690  19.076489
7     4.434821   4.382669   4.682912   4.410890   4.558500   4.600291
8     1.481178   1.726570   1.911538   1.509412   1.465622   1.710071
9          NaN        NaN        NaN        NaN        NaN        NaN
10    4.913644   5.136473   5.194500   5.446757   5.539568   5.363407
11   17.651398  17.865260  18.160876  18.200182  17.740845  17.538878
12    8.727298   8.406419   8.295096   7.518751   8.071132   7.748134
13    4.616300   3.555340   4.051383   3.565668   3.388226   3.646180
14    0.024366   0.023555   0.023219   0.022462   0.024260   0.026762
15   10.151039   9.744777   9.751985   9.249616  10.171465   9.046561
16    0.471267   0.531739   0.507237   0.521063   0.553283   0.559693
17    0.098376   0.115526   0.130557   0.127633   0.125717   0.137496
18    0.299529   0.301631   0.332728   0.357159   0.393937   0.412011
19    6.445333   6.925435   6.772088   5.731194   5.964900   6.715381
20   19.647089  25.915957  26.708212  23.811708  23.585481  22.413335
21    4.957324   4.938208   4.290906   4.629529   4.583343   5.091833
22    4.647461   4.677514   5.354936   5.526103   5.716135   6.475390
23    6.462447   6.330314   6.623164   6.439684   6.642697   6.762517
24    1.526093   1.597516   1.425287   1.868958   1.676106   1.826861
25   10.116176  11.246039   9.943759   7.262935   9.347122   6.872359
26    1.621907   1.306169   1.378966   1.433545   1.532871   1.602029
27    1.839394   1.901372   2.008670   1.883812   2.132938   2.211587
28    4.986413   4.939794   5.844583   5.807258   5.285997   5.449514
29   13.132862  22.450182  24.046884  20.486247  21.105946  24.607178
..         ...        ...        ...        ...        ...        ...
234   2.747693   2.762456   2.862069   2.765485   2.864984   2.894576
235   0.171352   0.172164   0.187073   0.208196   0.211509   0.217131
236   3.636029   3.588850   3.770655   3.844012   3.856529   3.860250
237   1.262133   1.110593   1.174807   1.274198   1.126823   0.981822
238   0.982909   1.043875   1.134883   1.229591   1.207519   1.270879
239   0.884319   0.891708   0.908547   0.871235   0.850715   0.840118
240  32.748910  34.732954  33.743586  33.969786  36.092933  35.162088
241   2.254981   2.341263   2.385393   2.355950   2.599658   2.417982
242   3.804564   4.090077   4.031512   3.894703   4.120215   4.370561
243   0.723488   1.074002   1.063926   1.053635   0.696420   0.690064
244   0.148359   0.140649   0.141951   0.132512   0.154162   0.170126
245   0.085872   0.094461   0.100755   0.103167   0.115583   0.121524
246   6.976805   6.907397   6.723650   5.647810   6.641350   6.265962
247   5.041365   5.248862   5.527812   5.599058   5.982706   6.403581
248   1.995853   1.797409   2.466682   2.396864   1.893043   2.292942
249  19.094067  19.217898  18.461764  17.157738  17.442166  16.973456
250   4.541206   4.473745   4.538018   3.858172   3.647049   3.874801
251   2.020256   2.084918   2.082664   2.852965   2.012716   1.811013
252   6.223186   5.806267   6.364740   6.289128   6.513377   6.001459
253   5.982556   6.079293   6.301672   6.239460   6.330774   6.308591
254        NaN        NaN        NaN        NaN        NaN        NaN
255   1.207429   1.221016   1.360812   1.469013   1.613360   1.701422
256   0.222104   0.450137   0.423103   0.524345   0.512118   0.545795
257   4.630496   4.665488   4.756160   4.656044   4.828069   4.967581
258   0.911212   0.945487   0.979060   1.011854   1.004361   1.074708
259        NaN        NaN        NaN        NaN        NaN        NaN
260   1.007360   0.964139   0.999238   1.069059   0.992602   0.810900
261   9.073200   9.352665   9.854219   9.870597   9.190699   9.004033
262   0.185076   0.151567   0.165936   0.186396   0.194337   0.205911
263   0.796028   0.741658   0.573101   0.405716   0.552146   0.664751

          2012       2013       2014
0    13.155542   8.351294   8.408363
1     0.350371   0.315602   0.299445
2     1.330843   1.254617   1.291328
3     1.692908   1.749211   1.978763
4     5.916597   5.900753   5.832170
5     4.813631   4.650474   4.860234
6    19.817684  18.954164  23.302023
7     4.569384   4.462904   4.746797
8     1.976060   1.899712   1.902759
9          NaN        NaN        NaN
10    5.418447   5.360453   5.377649
11   17.066141  16.083474  15.370138
12    7.387077   7.368748   6.869868
13    3.824877   3.785069   3.931561
14    0.030297   0.030176   0.044485
15    8.546478   8.671352   8.328160
16    0.562347   0.580961   0.614214
17    0.158663   0.179132   0.162019
18    0.433488   0.442401   0.459142
19    6.119457   5.450696   5.871616
20   20.514851  23.804357  23.449755
21    5.292937   7.426540   6.323258
22    6.101280   6.080813   6.234719
23    6.679992   6.736652   6.701958
24    1.415826   1.491599   1.407601
25    7.356863   7.051815   8.838315
26    1.835469   1.818997   1.932419
27    2.343570   2.488417   2.594388
28    5.222107   5.127146   4.490178
29   24.180764  19.233592  22.124701
..         ...        ...        ...
234   2.992217   3.005566   3.032805
235   0.253605   0.371541   0.387014
236   3.966160   3.953797   3.967544
237   1.013263   1.079267   1.143966
238   1.362315   1.355221   1.461473
239   0.827960   0.823009   0.840453
240  33.855000  34.520032  34.163243
241   2.480446   2.511904   2.587060
242   4.419488   4.285301   4.491479
243   1.025734   1.016822   1.008526
244   0.194471   0.220730   0.221347
245   0.112110   0.129675   0.134656
246   6.487603   5.976642   5.020747
247   6.555614   6.605490   6.588135
248   2.559620   2.226236   1.973151
249  16.304287  16.314352  16.490608
250   3.889733   3.417442   3.420723
251   2.314348   1.911992   1.911345
252   6.649233   6.066461   6.025698
253   6.174050   6.057819   6.072834
254        NaN        NaN        NaN
255   1.572338   1.609112   1.803566
256   0.459329   0.420092   0.594993
257   4.996211   4.987739   4.969974
258   1.046640   1.038064   1.029788
259        NaN        NaN        NaN
260   0.749447   0.996885   0.864835
261   8.845033   8.673963   8.980119
262   0.249457   0.261113   0.288271
263   0.529703   0.775564   0.779956

[264 rows x 14 columns]

In [88]:
averages = {}
for index, row in co2.iterrows():
    total = 0
    totalyears = 0
    for i in range(2006, 2015):
        current = str(i)
        prev = str(i-1)
        if math.isnan(row[current]) is False and math.isnan(row[prev]) is False:
            totalyears += 1
            total += (row[current] - row[prev])
    #print(totalyears, ' ', row['Country Name'])
    if totalyears > 0:
        averages [row['Country Code']] = total/totalyears
    else: 
        averages [row['Country Code']] = float('NaN')


print(averages.values())

dict_values([-2.088038349188446, 0.027388530664914645, 0.03462092104728825, 0.06291834456322233, -0.163077998405797, 0.07686084179831504, -0.22892779313734835, 0.06728451565191919, 0.04919204812696249, nan, 0.06340560689401206, -0.19995263173684286, -0.23892240754633706, -0.017804590875592878, 0.0026375521120912604, -0.22524812106807682, 0.03491427186000396, 0.008682606880906388, 0.020432818996619917, -0.04274068608530435, 0.20531373136215494, 0.11477338916385665, 0.21661733482594553, 0.06438734654993056, -0.009007230632877375, -0.027779925843594455, 0.0663431729195633, 0.08181114370439742, -0.04978502566078616, 0.9352288464492037, 0.07624393918488842, 0.11513267503070182, 0.0010821286806835034, -0.23710272247500855, -0.0922701355715131, -0.13853193197154726, nan, 0.09543588670839734, 0.3356366197675581, 0.007048486129944557, 0.011416504834090251, 0.003997363047943452, 0.041229193085012744, 0.039061309974725976, -0.002779364373406217, 0.00068421999765595, 0.0015623568467774992, 0.05471545531582124, 0.08228342742640492, -0.8596869919796148, -0.06190588447008357, -0.22671173378490167, -0.2884968510570973, -0.08633353771853673, 0.02921376866909247, 0.022536110688465172, -0.3060404942730025, 0.005800916661588366, 0.05496963901229549, 0.23487975222668267, 0.04851311330188129, 0.21060465583370705, 0.010019019494753737, -0.10581904756463405, 0.06203730743262797, 0.0023527628670711267, -0.20852790008325903, -0.010056369876503893, -0.34035928449520075, 0.27575599846114546, 0.005822811613371835, -0.19595712095073953, 0.004545665705543144, -0.19507964541396522, -0.0015091566079994153, -0.16960185639922504, -0.3025887534779213, 0.03399217315202706, -0.07949594074675298, -0.27616644950859964, 0.13356051290841228, 0.023545920350533673, 0.33953963927216335, 0.002092682042642152, 0.007172854591358752, 0.0003571565604265729, -0.1653637875315154, -0.31116690892534976, 0.019327018742461358, -0.189149270665075, 0.021234292826868877, nan, 0.07979374830671818, -0.14009004379701354, -0.005073629927809107, 0.005636644100263075, 0.009040481058952015, -0.12358661287127558, 0.005164722718472893, -0.16514155017199272, 0.12975736987651582, 0.09144633579283158, 0.0005833748796675062, -0.013233558344380201, 0.03454252481879213, 0.00746143499875133, nan, 0.07349302373521836, nan, -0.3502457662644247, 0.1806537993060939, 0.06762181915141546, -0.1615474610832096, -0.039434158251192564, -0.321691482365833, -0.13687494889625773, -0.07589162592512795, -0.017797379438252117, 0.2951115042010664, 0.00809869135855974, 0.06257625521316987, 0.025397288952917308, -0.012316023011912825, 0.025046938509565644, 0.21811950689493523, -0.6892082946128385, 0.03313180967407571, 0.0059019663809884125, 0.025592732134414636, -0.0010742186473655009, 0.02126165239588751, 0.007478841751868328, 0.03778753558531426, 0.01144055768272635, -0.007948644104995517, -0.08280690499169086, 0.029528570068655478, 0.03530724991140599, 0.09199452988614304, 0.013051942653650443, 0.22948783484863888, 0.021560892472981565, -0.829169478487043, 0.016149617386024148, -0.17912150699340812, nan, 0.02719013930271699, nan, 0.0027958707144628064, 0.003936694715591825, 0.1537068113979242, 0.10056847584562788, -0.048124902455754036, 0.03564332885201263, 0.10855429985199165, -0.2066575071598817, 0.0014481341988819671, -0.14251192960476583, 0.01970730173393044, 0.04190232754004554, 0.023003108894560094, 0.4153555426139957, nan, 0.024729094052820016, 0.017739025973339984, 0.07434567458924718, 0.0008390927318630621, 0.1369861229636059, -0.3341932535777047, 0.04965821661131679, 0.4275984423376392, 0.0065073816503783705, -0.024198804512585468, 0.0006108337757445323, -0.13333772110258757, 0.01019202286255864, 0.01814012533374085, -0.23797595086273424, -0.06354597071910709, -0.16329552067363334, 0.39327452131279333, 0.19662626291748964, 0.0009440046504939841, 0.022317540673661738, 0.07205517125163736, 0.02089752866780338, -0.08184652564121642, 0.013346936060226867, -0.045541677905775124, 0.004635873289376702, nan, -0.17199007202641145, -0.20929016091595087, 0.023223706733551824, -0.030153291109778366, 0.0006840259387120234, -0.1825696311692114, -0.03416819326028412, -1.4994992038450587, -0.11201686709735457, 0.06711101172141849, 0.001698946187912363, 0.058361810074643056, 0.32171779428838815, 0.0028646392423007806, 0.010247521611935909, 0.35437894204008086, 0.0007857455907004805, 0.009818216426792752, -0.007760183480561499, nan, -0.0013354882330841242, -0.25055086714785524, -0.002752982914680155, 0.0033527094207924657, -0.0027955094425715274, 0.1528196012483047, 0.011059069000362791, 0.04855445504066975, -0.18486771980180214, -0.19088753871271902, -0.13690348154193582, 0.0007650903004984401, -0.32606426080910644, -0.3223925019798828, -0.1298219378659059, 0.16789515703088823, 0.001563715772489289, 0.23997701155889922, 0.004054079175096703, 0.014132100631366015, 0.09326960525322875, 0.029350576179529804, 0.2611916239222452, 0.03661832912357557, 0.023948815241579338, 0.04306531885555836, 0.0021008608226910207, 0.058361810074643104, -0.0027955094425715643, 0.5273979432727399, 0.038204724620806624, 0.11060833617407544, -0.00984576394986441, 0.009076120165842722, 0.006511398888759399, -0.22968387254495198, 0.20620799253212585, 0.02627449726905125, -0.34458631514647603, -0.11778451191436644, -0.012437625918898545, -0.015359076570134652, 0.04164464591397316, nan, 0.07105219295915867, 0.03497356329202457, 0.0496858793020528, 0.014784094666193435, nan, -0.01210817912942984, 0.04892924208676222, 0.010934703419026403, -0.00581593448408625])

In [89]:
# new_cols = [*list(co2.columns.values),'average C02 increase']
# co2_cleaned = pd.DataFrame(columns = new_cols)

co2 ['average rate of change'] = averages.values()

print(co2)

                                          Country Name Country Code  \
0                                                Aruba          ABW
1                                          Afghanistan          AFG
2                                               Angola          AGO
3                                              Albania          ALB
4                                              Andorra          AND
5                                           Arab World          ARB
6                                 United Arab Emirates          ARE
7                                            Argentina          ARG
8                                              Armenia          ARM
9                                       American Samoa          ASM
10                                 Antigua and Barbuda          ATG
11                                           Australia          AUS
12                                             Austria          AUT
13                                          Azerbaijan          AZE
14                                             Burundi          BDI
15                                             Belgium          BEL
16                                               Benin          BEN
17                                        Burkina Faso          BFA
18                                          Bangladesh          BGD
19                                            Bulgaria          BGR
20                                             Bahrain          BHR
21                                        Bahamas, The          BHS
22                              Bosnia and Herzegovina          BIH
23                                             Belarus          BLR
24                                              Belize          BLZ
25                                             Bermuda          BMU
26                                             Bolivia          BOL
27                                              Brazil          BRA
28                                            Barbados          BRB
29                                   Brunei Darussalam          BRN
..                                                 ...          ...
234  Latin America & the Caribbean (IDA & IBRD coun...          TLA
235                                        Timor-Leste          TLS
236  Middle East & North Africa (IDA & IBRD countries)          TMN
237                                              Tonga          TON
238                            South Asia (IDA & IBRD)          TSA
239          Sub-Saharan Africa (IDA & IBRD countries)          TSS
240                                Trinidad and Tobago          TTO
241                                            Tunisia          TUN
242                                             Turkey          TUR
243                                             Tuvalu          TUV
244                                           Tanzania          TZA
245                                             Uganda          UGA
246                                            Ukraine          UKR
247                                Upper middle income          UMC
248                                            Uruguay          URY
249                                      United States          USA
250                                         Uzbekistan          UZB
251                     St. Vincent and the Grenadines          VCT
252                                      Venezuela, RB          VEN
253                             British Virgin Islands          VGB
254                              Virgin Islands (U.S.)          VIR
255                                            Vietnam          VNM
256                                            Vanuatu          VUT
257                                              World          WLD
258                                              Samoa          WSM
259                                             Kosovo          XKX
260                                        Yemen, Rep.          YEM
261                                       South Africa          ZAF
262                                             Zambia          ZMB
263                                           Zimbabwe          ZWE

                             Indicator Name  Indicator Code       2005  \
0    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC  27.200708
1    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.052948
2    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.979740
3    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   1.412498
4    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   7.299872
5    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   4.168486
6    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC  25.362373
7    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   4.141237
8    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   1.460030
9    CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC        NaN
10   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   4.806998
11   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC  17.169711
12   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   9.020170
13   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   4.091802
14   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.020747
15   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC  10.355393
16   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.299985
17   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.083875
18   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.275247
19   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   6.256282
20   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC  21.601931
21   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   5.290297
22   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   4.285163
23   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   6.122472
24   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   1.488667
25   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   9.088334
26   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   1.335331
27   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   1.858088
28   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   4.938243
29   CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC  13.707642
..                                      ...             ...        ...
234  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   2.703240
235  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.171475
236  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   3.579957
237  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   1.125058
238  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.936217
239  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.865613
240  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC  29.416661
241  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   2.243217
242  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   3.496004
243  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   1.097138
244  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.139662
245  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.076053
246  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   7.087902
247  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   4.732263
248  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   1.736680
249  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC  19.591885
250  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   4.480783
251  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   2.023284
252  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   6.163929
253  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   5.698032
254  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC        NaN
255  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   1.164096
256  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.280231
257  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   4.522801
258  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.896731
259  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC        NaN
260  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.973808
261  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   8.539756
262  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.189859
263  CO2 emissions (metric tons per capita)  EN.ATM.CO2E.PC   0.832299

          2006       2007       2008       2009       2010       2011  \
0    26.948260  27.895574  26.230847  25.915833  24.670529  24.505835
1     0.063728   0.085418   0.154101   0.241723   0.293837   0.412017
2     1.098884   1.197844   1.181527   1.232495   1.243406   1.252789
3     1.302576   1.322335   1.484311   1.495600   1.578574   1.803715
4     6.746219   6.519466   6.427887   6.121652   6.122595   5.867130
5     4.268240   4.100226   4.390401   4.542151   4.615758   4.537755
6    23.631089  22.439801  22.823947  21.908556  19.443690  19.076489
7     4.434821   4.382669   4.682912   4.410890   4.558500   4.600291
8     1.481178   1.726570   1.911538   1.509412   1.465622   1.710071
9          NaN        NaN        NaN        NaN        NaN        NaN
10    4.913644   5.136473   5.194500   5.446757   5.539568   5.363407
11   17.651398  17.865260  18.160876  18.200182  17.740845  17.538878
12    8.727298   8.406419   8.295096   7.518751   8.071132   7.748134
13    4.616300   3.555340   4.051383   3.565668   3.388226   3.646180
14    0.024366   0.023555   0.023219   0.022462   0.024260   0.026762
15   10.151039   9.744777   9.751985   9.249616  10.171465   9.046561
16    0.471267   0.531739   0.507237   0.521063   0.553283   0.559693
17    0.098376   0.115526   0.130557   0.127633   0.125717   0.137496
18    0.299529   0.301631   0.332728   0.357159   0.393937   0.412011
19    6.445333   6.925435   6.772088   5.731194   5.964900   6.715381
20   19.647089  25.915957  26.708212  23.811708  23.585481  22.413335
21    4.957324   4.938208   4.290906   4.629529   4.583343   5.091833
22    4.647461   4.677514   5.354936   5.526103   5.716135   6.475390
23    6.462447   6.330314   6.623164   6.439684   6.642697   6.762517
24    1.526093   1.597516   1.425287   1.868958   1.676106   1.826861
25   10.116176  11.246039   9.943759   7.262935   9.347122   6.872359
26    1.621907   1.306169   1.378966   1.433545   1.532871   1.602029
27    1.839394   1.901372   2.008670   1.883812   2.132938   2.211587
28    4.986413   4.939794   5.844583   5.807258   5.285997   5.449514
29   13.132862  22.450182  24.046884  20.486247  21.105946  24.607178
..         ...        ...        ...        ...        ...        ...
234   2.747693   2.762456   2.862069   2.765485   2.864984   2.894576
235   0.171352   0.172164   0.187073   0.208196   0.211509   0.217131
236   3.636029   3.588850   3.770655   3.844012   3.856529   3.860250
237   1.262133   1.110593   1.174807   1.274198   1.126823   0.981822
238   0.982909   1.043875   1.134883   1.229591   1.207519   1.270879
239   0.884319   0.891708   0.908547   0.871235   0.850715   0.840118
240  32.748910  34.732954  33.743586  33.969786  36.092933  35.162088
241   2.254981   2.341263   2.385393   2.355950   2.599658   2.417982
242   3.804564   4.090077   4.031512   3.894703   4.120215   4.370561
243   0.723488   1.074002   1.063926   1.053635   0.696420   0.690064
244   0.148359   0.140649   0.141951   0.132512   0.154162   0.170126
245   0.085872   0.094461   0.100755   0.103167   0.115583   0.121524
246   6.976805   6.907397   6.723650   5.647810   6.641350   6.265962
247   5.041365   5.248862   5.527812   5.599058   5.982706   6.403581
248   1.995853   1.797409   2.466682   2.396864   1.893043   2.292942
249  19.094067  19.217898  18.461764  17.157738  17.442166  16.973456
250   4.541206   4.473745   4.538018   3.858172   3.647049   3.874801
251   2.020256   2.084918   2.082664   2.852965   2.012716   1.811013
252   6.223186   5.806267   6.364740   6.289128   6.513377   6.001459
253   5.982556   6.079293   6.301672   6.239460   6.330774   6.308591
254        NaN        NaN        NaN        NaN        NaN        NaN
255   1.207429   1.221016   1.360812   1.469013   1.613360   1.701422
256   0.222104   0.450137   0.423103   0.524345   0.512118   0.545795
257   4.630496   4.665488   4.756160   4.656044   4.828069   4.967581
258   0.911212   0.945487   0.979060   1.011854   1.004361   1.074708
259        NaN        NaN        NaN        NaN        NaN        NaN
260   1.007360   0.964139   0.999238   1.069059   0.992602   0.810900
261   9.073200   9.352665   9.854219   9.870597   9.190699   9.004033
262   0.185076   0.151567   0.165936   0.186396   0.194337   0.205911
263   0.796028   0.741658   0.573101   0.405716   0.552146   0.664751

          2012       2013       2014  average rate of change
0    13.155542   8.351294   8.408363               -2.088038
1     0.350371   0.315602   0.299445                0.027389
2     1.330843   1.254617   1.291328                0.034621
3     1.692908   1.749211   1.978763                0.062918
4     5.916597   5.900753   5.832170               -0.163078
5     4.813631   4.650474   4.860234                0.076861
6    19.817684  18.954164  23.302023               -0.228928
7     4.569384   4.462904   4.746797                0.067285
8     1.976060   1.899712   1.902759                0.049192
9          NaN        NaN        NaN                     NaN
10    5.418447   5.360453   5.377649                0.063406
11   17.066141  16.083474  15.370138               -0.199953
12    7.387077   7.368748   6.869868               -0.238922
13    3.824877   3.785069   3.931561               -0.017805
14    0.030297   0.030176   0.044485                0.002638
15    8.546478   8.671352   8.328160               -0.225248
16    0.562347   0.580961   0.614214                0.034914
17    0.158663   0.179132   0.162019                0.008683
18    0.433488   0.442401   0.459142                0.020433
19    6.119457   5.450696   5.871616               -0.042741
20   20.514851  23.804357  23.449755                0.205314
21    5.292937   7.426540   6.323258                0.114773
22    6.101280   6.080813   6.234719                0.216617
23    6.679992   6.736652   6.701958                0.064387
24    1.415826   1.491599   1.407601               -0.009007
25    7.356863   7.051815   8.838315               -0.027780
26    1.835469   1.818997   1.932419                0.066343
27    2.343570   2.488417   2.594388                0.081811
28    5.222107   5.127146   4.490178               -0.049785
29   24.180764  19.233592  22.124701                0.935229
..         ...        ...        ...                     ...
234   2.992217   3.005566   3.032805                0.036618
235   0.253605   0.371541   0.387014                0.023949
236   3.966160   3.953797   3.967544                0.043065
237   1.013263   1.079267   1.143966                0.002101
238   1.362315   1.355221   1.461473                0.058362
239   0.827960   0.823009   0.840453               -0.002796
240  33.855000  34.520032  34.163243                0.527398
241   2.480446   2.511904   2.587060                0.038205
242   4.419488   4.285301   4.491479                0.110608
243   1.025734   1.016822   1.008526               -0.009846
244   0.194471   0.220730   0.221347                0.009076
245   0.112110   0.129675   0.134656                0.006511
246   6.487603   5.976642   5.020747               -0.229684
247   6.555614   6.605490   6.588135                0.206208
248   2.559620   2.226236   1.973151                0.026274
249  16.304287  16.314352  16.490608               -0.344586
250   3.889733   3.417442   3.420723               -0.117785
251   2.314348   1.911992   1.911345               -0.012438
252   6.649233   6.066461   6.025698               -0.015359
253   6.174050   6.057819   6.072834                0.041645
254        NaN        NaN        NaN                     NaN
255   1.572338   1.609112   1.803566                0.071052
256   0.459329   0.420092   0.594993                0.034974
257   4.996211   4.987739   4.969974                0.049686
258   1.046640   1.038064   1.029788                0.014784
259        NaN        NaN        NaN                     NaN
260   0.749447   0.996885   0.864835               -0.012108
261   8.845033   8.673963   8.980119                0.048929
262   0.249457   0.261113   0.288271                0.010935
263   0.529703   0.775564   0.779956               -0.005816

[264 rows x 15 columns]

In [91]:
writer = pd.ExcelWriter('cleaned_co2.xlsx')
co2.to_excel(writer,'Sheet5')
writer.save()

In [103]:
for i in range(1960, 2018):
    string = str(i)
    if i < 2005 or i > 2017:
        del population[string]

In [104]:
averages = {}
for index, row in population.iterrows():
    total = 0
    totalyears = 0
    for i in range(2006, 2015):
        current = str(i)
        prev = str(i-1)
        if math.isnan(row[current]) is False and math.isnan(row[prev]) is False:
            totalyears += 1
            total += (row[current] - row[prev])
    #print(totalyears, ' ', row['Country Name'])
    if totalyears > 0:
        averages [row['Country Code']] = round(total/totalyears, 3)
    else: 
        averages [row['Country Code']] = float('NaN')


print(averages.values())

dict_values([418.222, 854135.778, 818658.222, -13598.111, 39.556, 8197588.889, 499033.889, 426225.222, -8337.667, -409.0, 1069.111, 345482.0, 35391.889, 127025.444, 274277.889, 81160.0, 256054.111, 462671.889, 1774908.667, -48337.111, 49692.111, 5880.0, -23947.556, -21044.889, 7601.889, 109.444, 159638.889, 1921752.444, 1041.778, 5171.778, 13312.111, 34746.778, 43053.556, 358149.778, -297509.667, 83503.778, 963.889, 162970.444, 6727777.778, 466116.333, 535456.556, 2107931.556, 128095.333, 500697.444, 16417.556, 5763.333, 56637.111, 44527.444, 17279.333, 2027.889, 1172.222, 13850.111, 34903.444, -165213.556, 14323.333, 239.0, 24893.667, 129808.667, 647208.444, 14260655.556, 43634229.778, 15153587.556, 1693792.333, 3384616.0, 240875.444, 1670490.778, 1009539.778, 84280.5, 314191.889, -4470.0, 2293299.0, 1342096.222, 10375298.333, 23935.111, 7109.889, 348526.778, 61.889, -242.333, 52509.667, 467994.889, -51444.444, 602283.778, 217.0, 236196.0, 52627.556, 38322.889, 41345.222, -10544.556, 379.0, -71.111, 314170.111, 285.0, 1383.0, 8117318.111, 46255.556, 159531.778, 17444554.111, -22623.444, 145451.333, -24510.778, 44396714.222, 75702752.556, 31306038.333, 10469411.556, 3157598.444, 20836626.778, 719.111, 16637846.667, nan, 55314.0, 887697.889, 888628.222, 3405.778, 142844.444, 313295.111, 13046.0, 343910.556, -55222.222, 237917.333, 1108440.222, 74766.667, 222287.667, 2014.778, 569.778, 284677.556, 167314.111, 6421027.222, 91374.556, 179603.0, 125500.778, 45713.333, 1411.889, 7073509.111, 20008249.889, 16044383.222, 252.778, 138493.556, 40854902.444, 75329799.444, 21804.667, 13421110.444, -43351.222, 10129.0, -27224.111, 11802.444, 402.667, 421890.222, 482.111, -4310.0, 583675.222, 9934.556, 8008194.222, 1749930.222, 93.667, 59285416.222, 1913.667, 462675.889, 3413.778, 382396.444, 6053642.556, 838.778, 44161.111, -1030.667, 698812.444, 103688.889, 3631.111, 447680.778, 507624.889, 2925584.333, 37644.0, 3977.778, 614418.889, 4169002.667, 70518.778, 60571.111, 57104.556, 298106.0, 193.222, 41755.556, 8308600.778, 161072.889, 629025.556, 3515176.667, 63724.556, 373660.444, 1536445.778, 132.0, 160119.556, -17078.889, 21173985.0, -31832.0, 134688.444, -11363.111, 84121.111, 108254.0, 28532.556, 5118672.889, 2288.667, 167728.444, -156745.111, 33460.333, 261513.556, 23241914.0, 763452.0, 758444.333, 366093.889, 133773.556, 11735.444, 157864.778, 28025.333, 379.667, 344800.0, -34465.889, 23658767.778, 380232.667, 23659712.333, 702085.556, 3959.556, 5442.444, 5093.556, 6834.0, 74059.778, 21024.889, 519.333, 944.556, 100942.111, 810.111, 389158.778, 14126508.111, 1654090.0, 171738.556, 332366.889, 167618.778, 79066.667, 7075139.556, 20703.333, 5945388.556, 526.778, 23241914.0, 23659712.333, 6395.444, 115714.0, 1014135.778, 97.889, 1424924.889, 1143266.444, -203689.222, 18430513.778, 10437.111, 2567325.111, 510077.778, 68.111, 439357.444, 713.333, -63.333, 915119.111, 5497.778, 83447117.556, 1373.444, 12891.111, 629266.667, 635442.778, 396535.333, 274627.0])

In [105]:
population['average population change'] = averages.values()

In [106]:
writer = pd.ExcelWriter('cleaned_population.xlsx')
population.to_excel(writer,'Sheet5')
writer.save()